# TODO: Add cleanup script that removes venv and required python version
name = "gaitmap_algos"
setup = [
    "poetry env use {python_path}",
    "poetry update",
    "poetry run poe commit_lock_if_changed",
    "poetry install"
]
command_template = "poetry run python {command}"

[challenge.stride_segmentation.egait_segmentation_validation_2014]
barth_dtw = "gaitmap_algos/stride_segmentation/dtw/barth_dtw/egait_segmentation_validation_2014.py"
barth_dtw_default = "gaitmap_algos/stride_segmentation/dtw/barth_dtw/egait_segmentation_validation_2014_default.py"
constrained_barth_dtw = "gaitmap_algos/stride_segmentation/dtw/constrained_barth_dtw/egait_segmentation_validation_2014.py"
constrained_barth_dtw_default = "gaitmap_algos/stride_segmentation/dtw/constrained_barth_dtw/egait_segmentation_validation_2014_default.py"
roth_hmm_default = "gaitmap_algos/stride_segmentation/roth_hmm/egait_segmentation_validation_2014_default.py"
roth_hmm_trained = "gaitmap_algos/stride_segmentation/roth_hmm/egait_segmentation_validation_2014_trained.py"


[challenge.stride_segmentation.egait_segmentation_validation_2014_original_label]
barth_dtw = "gaitmap_algos/stride_segmentation/dtw/barth_dtw/egait_segmentation_validation_2014_original_label.py"
barth_dtw_default = "gaitmap_algos/stride_segmentation/dtw/barth_dtw/egait_segmentation_validation_2014_original_label_default.py"
constrained_barth_dtw = "gaitmap_algos/stride_segmentation/dtw/constrained_barth_dtw/egait_segmentation_validation_2014_original_label.py"
constrained_barth_dtw_default = "gaitmap_algos/stride_segmentation/dtw/constrained_barth_dtw/egait_segmentation_validation_2014_original_label_default.py"
roth_hmm_default = "gaitmap_algos/stride_segmentation/roth_hmm/egait_segmentation_validation_2014_original_label_default.py"
roth_hmm_trained = "gaitmap_algos/stride_segmentation/roth_hmm/egait_segmentation_validation_2014_original_label_trained.py"


[challenge.stride_segmentation.sensor_position_comparison_instep]
barth_dtw = "gaitmap_algos/stride_segmentation/dtw/barth_dtw/sensor_position_comparison_instep.py"
barth_dtw_default = "gaitmap_algos/stride_segmentation/dtw/barth_dtw/sensor_position_comparison_instep_default.py"
constrained_barth_dtw = "gaitmap_algos/stride_segmentation/dtw/constrained_barth_dtw/sensor_position_comparison_instep.py"
constrained_barth_dtw_default = "gaitmap_algos/stride_segmentation/dtw/constrained_barth_dtw/sensor_position_comparison_instep_default.py"
roth_hmm_default = "gaitmap_algos/stride_segmentation/roth_hmm/sensor_position_comparison_instep_default.py"
roth_hmm_trained = "gaitmap_algos/stride_segmentation/roth_hmm/sensor_position_comparison_instep_trained.py"


[challenge.full_pipeline.kluge_2017]
mad_classic = "gaitmap_algos/full_pipeline/mad_classic/kluge_2017.py"
mad_modern = "gaitmap_algos/full_pipeline/mad_modern/kluge_2017.py"
mad_modern_optimized_zupt = "gaitmap_algos/full_pipeline/mad_modern/kluge_2017_optimized_zupt.py"


[challenge.full_pipeline.sensor_position_comparison_instep]
mad_classic = "gaitmap_algos/full_pipeline/mad_classic/sensor_position_comparison_instep.py"
mad_modern = "gaitmap_algos/full_pipeline/mad_modern/sensor_position_comparison_instep.py"
mad_modern_optimized_zupt = "gaitmap_algos/full_pipeline/mad_modern/sensor_position_comparison_instep_optimized_zupt.py"
